site_name: Cours de Yassine Benabbas
site_url: https://yostane.github.io/lectures/
repo_url: https://github.com/yostane/lectures
repo_name: yostane/lectures
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yostane
  alternate:
    - name: Français
      link: ""
      lang: fr
    - name: English
      link: ""
      lang: en

nav:
  - index.md
  - Java:
      - java/index.md
      - java/java-tour.md
      - Exercices:
          - java/java-exercices-1.md
          - java/java-exercices-arrays.md
          - java/java-exercices-lists-maps.md
          - java/java-exercices-streams.md
          - java/java-exercices-misc.md
      - java/jee.md
      - java/javafx.md
  - .Net:
      - dotnet/index.md
      - dotnet/csharp-tour.md
      - dotnet/csharp-exercices.md
      - dotnet/dotnet.md
      - dotnet/dotnet-exercices.md
      - dotnet/asp-dot-net.md
      - dotnet/asp-dot-net-exercices.md
      - dotnet/monogame.md
      - dotnet/maui.md
  - JavaScript:
      - js/index.md
      - js/js.md
      - js/reactjs.md
      - js/webia.md
      - js/projets.md
  - Python:
      - python/index.md
      - python/index.en.md
      - python/python-tour.md
      - python/python-tour.en.md
      - python/python-exercices.md
      - python/python-exercices.en.md
      - python/python-poo.md
      - python/python-poo.en.md
      - python/python-poo-exercices.md
      - python/python-func.md
      - python/python-func-exercices.md
      - python/tkinter.md
      - python/tkinter.en.md
      - python/tkinter-exercices.md
      - python/django-tour.md
      - python/django-tour.en.md
      - Data science:
          - python/datascience/index.ipynb
          - python/datascience/exercices.md
          - python/datascience/ex-01.ipynb
          - python/datascience/ex-02.ipynb
          - python/datascience/streamlit.md
      - python/projects-type.md
  - go:
      - go/index.md
      - go/rest-api.md
      - go/exercices.md
      - go/projets.md
  - Test:
      - test/index.md
      - test/generalites.md
      - test/librairies.md
      - test/bdd.md
      - test/projet.md
  - Archi. logicielle:
      - archi/index.md
      - archi/katas.md
      - archi/kata-examples.md
      - archi/archi-doc.md
      - Sujets de veille:
          - archi/sujets-vrac.md
          - archi/sujets-2324.md
          - Sujets 24-25:
              - archi/2425/index.md
              - archi/2425/adr.md
              - archi/2425/unclebob.md
              - archi/2425/cloud_vs_onpremise.md
              - archi/2425/saas.md
              - archi/2425/oidc.md
              - archi/2425/kafka.md
              - archi/2425/kube.md
              - archi/2425/structurizr.md
  - Dév. desktop:
      - desktopdev/index.md
      - desktopdev/features.md
      - desktopdev/electronjs.md
      - desktopdev/project.md
  - Prog. distribuée:
      - distrib/index.md
      - distrib/spark.md
      - distrib/exos.md
      - Dask et Coiled:
          - distrib/dask/dask-df.ipynb
          - distrib/dask/dask-array.ipynb
          - distrib/dask/dask-bag.ipynb
          - distrib/dask/dask-misc.ipynb
          - distrib/dask/coiled.md
  - IoT:
      - iot/index.md
      - iot/deviot.md
      - iot/exo_mqtt.md
      - iot/exo_embedded.md
  - Blog:
      - blog/index.md

plugins:
  - mkdocs-jupyter
  - search
  - blog
  - glightbox
  - i18n:
      languages:
        fr: "Français"
        en: "English"
      default_language: "fr"

theme:
  logo: img/logo.jpg
  favicon: img/logo.jpg
  name: material
  features:
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - navigation.tabs
    - navigation.path
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: light green
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: green

markdown_extensions:
  - pymdownx.snippets
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      base_path:
        - includes
        - material
        - material/java/common
        - material/dotnet/csharp
        - material/dotnet/dotnet
        - material/dotnet
        - material/js/poo
        - material/js/functional
        - material/js/generalities
        - material/js/classes
        - material/python/tour
        - material/python/poo
        - material/python/demos
        - material/python
      auto_append:
        - "includes/abbreviations.md"
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
