create schema api;

--  endpoint /todos
create table api.todos (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz
);
insert into api.todos (task) values
  ('finish tutorial 0'), ('pat self on back');

-- Make a role to use for anonymous web requests. When a request comes in, PostgREST will switch into this role in the database to run queries.
create role web_anon nologin;
-- The web_anon role has permission to access things in the api schema, and to read rows in the todos table.
grant usage on schema api to web_anon;
grant select on api.todos to web_anon;
-- It’s a good practice to create a dedicated role for connecting to the database:
create role authenticator noinherit login password 'mysecretpassword';
-- authenticator can switch to the web_anon role:
grant web_anon to authenticator;