extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
rules:
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
env:
  jest/globals: true
